version: '3.8'

services:
  besu-node1:
    image: hyperledger/besu:latest
    container_name: besu-node1
    networks:
      besu-net:
        ipv4_address: 172.25.0.11
    volumes:
      - besu-node1-data:/var/lib/besu
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
    command: >
      --network=dev
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
      --host-whitelist="*"

  besu-node2:
    image: hyperledger/besu:latest
    container_name: besu-node2
    networks:
      besu-net:
        ipv4_address: 172.25.0.12
    volumes:
      - besu-node2-data:/var/lib/besu
    ports:
      - "8555:8545"
      - "8556:8546"
      - "8557:8547"
    command: >
      --network=dev
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
      --host-whitelist="*"

  besu-node3:
    image: hyperledger/besu:latest
    container_name: besu-node3
    networks:
      besu-net:
        ipv4_address: 172.25.0.13
    volumes:
      - besu-node3-data:/var/lib/besu
    ports:
      - "8565:8545"
      - "8566:8546"
      - "8567:8547"
    command: >
      --network=dev
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
      --host-whitelist="*"

networks:
  besu-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  besu-node1-data:
  besu-node2-data:
  besu-node3-data:

