version: "3.8"
services:
  booteth:
    image: hyperledger/besu:latest
    container_name: booteth
    volumes:
      - ./data/booteth:/booteth/
      - ./data/genesis.json:/booteth/genesis.json
      - ./config/booteth/config.toml:/booteth/config.toml
    ports:
      - 30303:30303
      - 8545:8545
      - 8549:8549
    command: --config-file=/booteth/config.toml
    networks:
      besu_network:
        ipv4_address: 172.28.5.1

  nodeth1:
    image: hyperledger/besu:latest
    container_name: nodeth1
    volumes:
      - ./data/nodeth1:/nodeth1/
      - ./data/genesis.json:/nodeth1/genesis.json
      - ./config/nodeth1/config.toml:/nodeth1/config.toml
    ports:
      - 8546:8545
    command: --config-file=/nodeth1/config.toml
    networks:
      besu_network:
        ipv4_address: 172.28.5.2

  nodeth2:
    image: hyperledger/besu:latest
    depends_on:
      - booteth
    container_name: nodeth2
    volumes:
      - ./data/nodeth2:/nodeth2/
      - ./data/genesis.json:/nodeth2/genesis.json
      - ./config/nodeth2/config.toml:/nodeth2/config.toml
    ports:
      - 8547:8545
    command: --config-file=/nodeth2/config.toml
    networks:
      besu_network:
        ipv4_address: 172.28.5.3

  nodeth3:
    image: hyperledger/besu:latest
    depends_on:
      - booteth
    container_name: nodeth3
    volumes:
      - ./data/nodeth3:/nodeth3/
      - ./data/genesis.json:/nodeth3/genesis.json
      - ./config/nodeth3/config.toml:/nodeth3/config.toml
    ports:
      - 8548:8545
    command: --config-file=/nodeth3/config.toml
    networks:
      besu_network:
        ipv4_address: 172.28.5.4

networks:
  besu_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
